# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShotForTheHeart', '0003_customuser_activation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_eliminated',
            field=models.SmallIntegerField(default=0),
        ),
    ]
