# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 16:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShotForTheHeart', '0004_auto_20160604_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money_raised',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
