# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShotForTheHeart', '0005_customuser_money_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_location', models.CharField(blank=True, max_length=50)),
                ('fundraising_link', models.CharField(blank=True, max_length=127)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('users_needing_target', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='participating_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ShotForTheHeart.Game'),
        ),
    ]
