# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShotForTheHeart', '0006_auto_20160727_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
