# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShotForTheHeart', '0008_auto_20160730_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='target_id',
            new_name='target',
        ),
    ]
